auth_token: 2181e986-0b74-460f-bd1a-81f7062ec9cb
artists:
  8D PARADISE: 86271
  8DVOLUME: 86108
  DJMVS: 85774
  DZINNINI: 86366
  EBLN: 86276
  HWAREYOU?: 85756
  Himerkina Bella: 86373
  JISUO: 86333
  K-POP SQUAD: 86326
  KAZIOL: 86370
  LiSO4ka: 86357
  Tommy Pdras: 86277
  wiolets: 85809
  "\u0420\u041E\u0417\xC9": 86338
default:
  genre_id: 196
  label_id: 86276
  platform_ids: []
labels:
  8D PARADISE: 41602
  8DVOLUME: 41515
  DJMVS: 41344
  DZINNINI: 41653
  EBLN: 41605
  HWAREYOU?: 41334
  Himerkina Bella: 41657
  JISUO: 41628
  K-POP SQUAD: 41623
  KAZIOL: 41655
  LiSO4ka: 41647
  wiolets: 41371
  "\u0420\u041E\u0417\xC9": 41631
presets:
  8D PARADISE:
    label_id: 41602
    language_id: 7
    recording_year: 2025
    composers: []
    lyricists: []
    explicit: false
    track_date: '2025-01-01'
  8DVOLUME:
    label_id: 41515
    language_id: 7
    recording_year: 2025
    composers: []
    lyricists: []
    explicit: false
    track_date: '2025-01-01'
  DJMVS:
    label_id: 41344
    language_id: 7
    recording_year: 2025
    composers: []
    lyricists: []
    explicit: false
    track_date: '2025-01-01'
  DZINNINI:
    label_id: 41653
    language_id: 7
    recording_year: 2025
    composers: []
    lyricists: []
    explicit: false
    track_date: '2025-01-01'
  EBLN:
    label_id: 41605
    language_id: 7
    recording_year: 2025
    composers:
      - 79130
    lyricists:
      - 79130
    genre_id: 196
    explicit: false
    track_date: '2025-01-01'
  HWAREYOU?:
    label_id: 41334
    language_id: 7
    recording_year: 2025
    composers: []
    lyricists: []
    explicit: false
    track_date: '2025-01-01'
  Himerkina Bella:
    label_id: 41657
    language_id: 7
    recording_year: 2025
    composers: []
    lyricists: []
    explicit: false
    track_date: '2025-01-01'
  JISUO:
    label_id: 41628
    language_id: 7
    recording_year: 2025
    composers: []
    lyricists: []
    explicit: false
    track_date: '2025-01-01'
  K-POP SQUAD:
    label_id: 41623
    language_id: 7
    recording_year: 2025
    composers: []
    lyricists: []
    explicit: false
    track_date: '2025-01-01'
  KAZIOL:
    label_id: 41655
    language_id: 7
    recording_year: 2025
    composers: []
    lyricists: []
    explicit: false
    track_date: '2025-01-01'
  LiSO4ka:
    label_id: 41647
    language_id: 7
    recording_year: 2025
    composers: []
    lyricists: []
    explicit: false
    track_date: '2025-01-01'
  Tommy Pdras:
    label_id: 41657
    language_id: 7
    recording_year: 2025
    composers: []
    lyricists: []
    explicit: false
    track_date: '2025-01-01'
  wiolets:
    label_id: 41371
    language_id: 7
    recording_year: 2025
    composers: []
    lyricists: []
    explicit: false
    track_date: '2025-01-01'
  "\u0420\u041E\u0417\xC9":
    label_id: 41631
    language_id: 7
    recording_year: 2025
    composers: []
    lyricists: []
    explicit: false
    track_date: '2025-01-01'
